### ISSUE TITLE
Packaging Fider for Nix - I have some questions

### ISSUE THREAD

**Issue by drupol** [getfider/fider#1168]
Hello,

I'm trying to package Fider for Nix, you can follow my work at https://github.com/NixOS/nixpkgs/pull/313713

I'm unable to run the Fider service in the tests, the issue is:

```
vm-test-run-fider-server> machine # [  119.582670] postgres[1144]: [1144] LOG:  listening on Unix socket "/run/postgresql/.s.PGSQL.5432"
vm-test-run-fider-server> machine # [  119.637532] postgres[1147]: [1147] LOG:  database system was shut down at 2024-05-22 19:38:14 GMT
vm-test-run-fider-server> machine # [  119.696503] postgres[1144]: [1144] LOG:  database system is ready to accept connections
vm-test-run-fider-server> machine # [  122.833745] postgresql-post-start[1167]: CREATE DATABASE
vm-test-run-fider-server> machine # [  123.541314] postgresql-post-start[1175]: CREATE ROLE
vm-test-run-fider-server> machine # [  123.885283] postgresql-post-start[1178]: ALTER ROLE
vm-test-run-fider-server> machine # [  124.181022] postgresql-post-start[1180]: ALTER DATABASE
vm-test-run-fider-server> machine # [  124.278921] systemd[1]: Started PostgreSQL Server.
vm-test-run-fider-server> machine # [  124.565474] systemd[1]: Started Fider server.
vm-test-run-fider-server> machine # [  124.597877] systemd[1]: Reached target Multi-User System.
vm-test-run-fider-server> machine # [  124.623459] systemd[1]: Startup finished in 28.635s (kernel) + 1min 35.981s (userspace) = 2min 4.617s.
vm-test-run-fider-server> machine # [  126.686166] fider[1187]: panic: Error Trace:
vm-test-run-fider-server> machine # [  126.690920] fider[1187]: - failed to list etc/ blobs (app/cmd/server.go:82)
vm-test-run-fider-server> machine # [  126.692808] fider[1187]: - failed to open transaction (app/services/blob/sql/sql.go:62)
vm-test-run-fider-server> machine # [  126.694433] fider[1187]: - failed to start new transaction (app/pkg/dbx/dbx.go:319)
vm-test-run-fider-server> machine # [  126.696359] fider[1187]: - pq: SSL is not enabled on the server
vm-test-run-fider-server> machine # [  126.696890] fider[1187]: goroutine 1 [running]:
vm-test-run-fider-server> machine # [  126.698884] fider[1187]: github.com/getfider/fider/app/cmd.copyEtcFiles({0x1ee5aa0, 0xc00041b7a0})
vm-test-run-fider-server> machine # [  126.700389] fider[1187]:         github.com/getfider/fider/app/cmd/server.go:82 +0x4e7
vm-test-run-fider-server> machine # [  126.702590] fider[1187]: github.com/getfider/fider/app/cmd.RunServer()
vm-test-run-fider-server> machine # [  126.703739] fider[1187]:         github.com/getfider/fider/app/cmd/server.go:48 +0x2bc
vm-test-run-fider-server> machine # [  126.705492] fider[1187]: main.main()
vm-test-run-fider-server> machine # [  126.705957] fider[1187]:         github.com/getfider/fider/main.go:17 +0xa5
vm-test-run-fider-server> machine # [  126.726259] systemd[1]: fider.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
vm-test-run-fider-server> machine # [  126.731411] systemd[1]: fider.service: Failed with result 'exit-code'.
vm-test-run-fider-server> machine # [  126.754526] systemd[1]: fider.service: Consumed 1.032s CPU time, 1.6M memory peak, 0B memory swap peak, no IO, received 297B IP traffic, sent 448B IP traffic.
vm-test-run-fider-server> machine # [  126.832543] systemd[1]: fider.service: Scheduled restart job, restart counter is at 1.
vm-test-run-fider-server> machine # [  126.877785] systemd[1]: Started Fider server.
```

I'm trying to understand why it fails on:

```
vm-test-run-fider-server> machine # [  126.690920] fider[1187]: - failed to list etc/ blobs (app/cmd/server.go:82)
```

Can you please let me know why Fider need to copy stuff from `/etc` ?
Is there a way to modify that location with environment variables?

Thanks!

**Comment by drupol** [comment]
No response from the maintainer, closing this.
