### ISSUE TITLE
Try to create a «tenant» but get a 500 error code

### ISSUE THREAD

**Issue by sapiens-sapide** [getfider/fider#135]
Context: a brand new installation on a freebsd server. 
Fider service is started. I connect to `myserver.name.tld:8080` and get redirected to the signup page.
I fill the form with a name, an email and a project name.
When I click the confirm button, the POST action fails with a 500 error. 
POST payload:
```
{"tenantName":"project_name","name":"my_name","email":"email@provider.tld"}
```
server logs : 
```
DEBUG [2017-10-02T16:21:00+02:00] HTTP Request GET /signup
DEBUG [2017-10-02T16:21:00+02:00] SELECT id, name, subdomain, cname, invitation, welcome_message, status FROM tenants ORDER BY id LIMIT 1 []
DEBUG [2017-10-02T16:21:35+02:00] HTTP Request POST /api/tenants
DEBUG [2017-10-02T16:21:35+02:00] SELECT id FROM tenants WHERE subdomain = $1 [default]
DEBUG [2017-10-02T16:21:35+02:00] INSERT INTO tenants (name, subdomain, created_on, cname, invitation, welcome_message, status)  VALUES ($1, $2, $3, '', '', '', $4)  RETURNING id [project_name default 2017-10-02 16:21:35.4337588 +0200 CEST m=+1238.418072098 2]
DEBUG [2017-10-02T16:21:35+02:00] SELECT id, name, subdomain, cname, invitation, welcome_message, status FROM tenants WHERE subdomain = $1 OR cname = $2 ORDER BY cname DESC [default default]
DEBUG [2017-10-02T16:21:35+02:00] INSERT INTO signin_requests (tenant_id, email, created_on, expires_on, key, name) VALUES ($1, $2, $3, $4, $5, $6) [5 email@provider.tld 2017-10-02 16:21:35.434309439 +0200 CEST m=+1238.418622753 2017-10-04 16:21:35.434309846 +0200 CEST m=+174038.418623091 1b47aaf02b43453b975c2903d3e92caa my_name]
ERROR [2017-10-02T16:21:37+02:00] 535 5.7.8 Error: authentication failed:
goroutine 9 [running]:
runtime/debug.Stack(0xc4205336d8, 0x886200, 0xc420199620)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/getfider/fider/app/middlewares.Setup.func1.1.1(0xc420414380, 0xc420533b60)
	/usr/local/goland/src/github.com/getfider/fider/app/middlewares/setup.go:47 +0x6e
panic(0x886200, 0xc420199620)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/getfider/fider/app/pkg/web.(*Context).Failure(0xc420533918, 0xb97ae0, 0xc420199620, 0xc4200a2800, 0x16)
	/usr/local/goland/src/github.com/getfider/fider/app/pkg/web/context.go:90 +0x3e
github.com/getfider/fider/app/handlers.CreateTenant.func1(0xba5060, 0xc4204143c0, 0xc4204143c0, 0x90c8a0)
	/usr/local/goland/src/github.com/getfider/fider/app/handlers/signup.go:80 +0xa15
github.com/getfider/fider/app/pkg/web.wrapFunc.func1(0xba5060, 0xc4204143c0, 0xba5060, 0xc4204143c0)
	/usr/local/goland/src/github.com/getfider/fider/app/pkg/web/engine.go:145 +0x39
github.com/getfider/fider/app/pkg/web.wrapMiddleware.func1.1(0xba5060, 0xc4204143a0, 0x41297c, 0xc4204143a0)
	/usr/local/goland/src/github.com/getfider/fider/app/pkg/web/engine.go:137 +0x75
github.com/getfider/fider/app/middlewares.AddServices.func1.1(0xba5060, 0xc4204143a0, 0xc4204143a0, 0x90c8a0)
	/usr/local/goland/src/github.com/getfider/fider/app/middlewares/setup.go:78 +0x1a1
github.com/getfider/fider/app/pkg/web.wrapFunc.func1(0xba5060, 0xc4204143a0, 0xba5060, 0xc4204143a0)
	/usr/local/goland/src/github.com/getfider/fider/app/pkg/web/engine.go:145 +0x39
github.com/getfider/fider/app/pkg/web.wrapMiddleware.func1.1(0xba4e80, 0xc42012a000, 0xc420414380, 0xc42004fb60)
	/usr/local/goland/src/github.com/getfider/fider/app/pkg/web/engine.go:137 +0x75
github.com/getfider/fider/app/middlewares.Setup.func1.1(0xba4e80, 0xc42012a000, 0x0, 0x0)
	/usr/local/goland/src/github.com/getfider/fider/app/middlewares/setup.go:56 +0x451
github.com/getfider/fider/app/pkg/web.wrapFunc.func1(0xba4e80, 0xc42012a000, 0x20, 0x8bafc0)
	/usr/local/goland/src/github.com/getfider/fider/app/pkg/web/engine.go:145 +0x39
github.com/getfider/fider/vendor/github.com/labstack/echo.(*Echo).Add.func1(0xba4e80, 0xc42012a000, 0xc4202d4280, 0xb9d2a0)
	/usr/local/goland/src/github.com/getfider/fider/vendor/github.com/labstack/echo/echo.go:473 +0x87
github.com/getfider/fider/vendor/github.com/labstack/echo/middleware.GzipWithConfig.func1.1(0xba4e80, 0xc42012a000, 0x0, 0x0)
	/usr/local/goland/src/github.com/getfider/fider/vendor/github.com/labstack/echo/middleware/compress.go:92 +0x17f
github.com/getfider/fider/vendor/github.com/labstack/echo.(*Echo).ServeHTTP.func1(0xba4e80, 0xc42012a000, 0xc420084d58, 0x90bd60)
	/usr/local/goland/src/github.com/getfider/fider/vendor/github.com/labstack/echo/echo.go:570 +0x108
github.com/getfider/fider/vendor/github.com/labstack/echo.(*Echo).ServeHTTP(0xc420084d00, 0xb9d2a0, 0xc4204c8000, 0xc420238000)
	/usr/local/goland/src/github.com/getfider/fider/vendor/github.com/labstack/echo/echo.go:579 +0x229
net/http.serverHandler.ServeHTTP(0xc420097040, 0xb9d2a0, 0xc4204c8000, 0xc420238000)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc42045efa0, 0xb9d9e0, 0xc42008c200)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288
```

*NB* : No Oauth services have been configured in env variables.

**Comment by goenning** [comment]
That’s an SMTP Auth error, your credentials are probably wrong.

The email address you provide must also be valid as you’ll be require access to its inbox to click the confirmation link.

**Comment by sapiens-sapide** [comment]
Thanks @goenning for the help. It works now. May I suggest to improve error messages ?

Regards,
Stan.

**Comment by goenning** [comment]
Glad to hear it worked Stan! 

Thanks for the suggestion, I agree on that. There's much to improve on logging and errors messages.
