### ISSUE TITLE
Test failure: TestPanicked fails with Go 1.13.1

### ISSUE THREAD

**Issue by mdemierre** [getfider/fider#778]
Hi, I just cloned the latest master and tried to run the tests. I see the following failure:

```plaintext
--- FAIL: TestPanicked (0.00s)
    assert.go:101: Error Trace: 
        - app/pkg/errors/errors_test.go:91
        - ContainsSubstring assertion failed. 
         Substring: 
        		 
        - github.com/getfider/fider/app/pkg/errors_test.TestPanicked:97 (app/pkg/errors/errors.go:40)
        - Boom!
         Actual: 
        		 [string] Error Trace: 
        - goroutine 25 [running]:
        runtime/debug.Stack(0x6bb040, 0xc000097990, 0x0)
        	/usr/lib/go/src/runtime/debug/stack.go:24 +0xab
        github.com/getfider/fider/app/pkg/errors.Panicked(0x63aca0, 0x6b7930, 0x6b7930, 0xc0000182e9)
        	/home/marc/go/src/github.com/getfider/fider/app/pkg/errors/errors.go:41 +0xf5
        github.com/getfider/fider/app/pkg/errors_test.TestPanicked.func1()
        	/home/marc/go/src/github.com/getfider/fider/app/pkg/errors/errors_test.go:86 +0x69
        panic(0x63aca0, 0x6b7930)
        	/usr/lib/go/src/runtime/panic.go:679 +0x1b2
        github.com/getfider/fider/app/pkg/errors_test.TestPanicked(0xc0000ec600)
        	/home/marc/go/src/github.com/getfider/fider/app/pkg/errors/errors_test.go:97 +0x7f
        testing.tRunner(0xc0000ec600, 0x689c88)
        	/usr/lib/go/src/testing/testing.go:909 +0x19a
        created by testing.(*T).Run
        	/usr/lib/go/src/testing/testing.go:960 +0x652
         (app/pkg/errors/errors.go:41)
        - github.com/getfider/fider/app/pkg/errors_test.TestPanicked:84 (app/pkg/errors/errors.go:40)
        - Boom!
FAIL
FAIL	github.com/getfider/fider/app/pkg/errors	0.013s
```

Apparently, my stacktrace shows the place where the line where `defer` is declared (`84`) rather than the line where the panic is triggered (`97`).

My Go version is the following:

``` 
go version go1.13.1 linux/amd64
```

Changing the line number `97` -> `84` makes it pass, but of course I expect it to break runs on your side.

Can you reproduce the issue?

**Comment by goenning** [comment]
Yep, I had the same error. That test will have to change when we upgrade Fider to Go 1.13
