### ISSUE TITLE
Error deploying Heroku

### ISSUE THREAD

**Issue by buremba** [getfider/fider#821]
I tried to deploy Fider to Heroku following the docs but got this error:

```
2019-11-14T10:17:27.218828+00:00 heroku[web.1]: State changed from crashed to starting
2019-11-14T10:17:28.092990+00:00 heroku[web.1]: Starting process with command `./bin/fider migrate && ./bin/fider`
2019-11-14T10:17:29.805915+00:00 app[web.1]: INFO [2019-11-14T10:17:29Z] [MIGRATE] [FY0Qolzqqc0XimT73iKyjhMw11Mt4sU1] Running migrations...
2019-11-14T10:17:29.806611+00:00 app[web.1]: INFO [2019-11-14T10:17:29Z] [MIGRATE] [FY0Qolzqqc0XimT73iKyjhMw11Mt4sU1] Found total of 63 migration files.
2019-11-14T10:17:31.778592+00:00 app[web.1]: INFO [2019-11-14T10:17:31Z] [MIGRATE] [FY0Qolzqqc0XimT73iKyjhMw11Mt4sU1] Current version is 201904091921
2019-11-14T10:17:31.778707+00:00 app[web.1]: INFO [2019-11-14T10:17:31Z] [MIGRATE] [FY0Qolzqqc0XimT73iKyjhMw11Mt4sU1] Migrations are already up to date.
2019-11-14T10:17:32.586308+00:00 app[web.1]: panic: Path 'dist' not found
2019-11-14T10:17:32.586327+00:00 app[web.1]:
2019-11-14T10:17:32.586329+00:00 app[web.1]: goroutine 1 [running]:
2019-11-14T10:17:32.586336+00:00 app[web.1]: github.com/getfider/fider/app/pkg/web.(*Group).Static(0xc00033dcf0, 0xe241f5, 0x11, 0xe18125, 0x4)
2019-11-14T10:17:32.586367+00:00 app[web.1]: /tmp/build_72b16a0659f32d6eae7f03ceab607604/app/pkg/web/engine.go:281 +0x283
2019-11-14T10:17:32.586377+00:00 app[web.1]: github.com/getfider/fider/app/cmd.routes(0xc0003e8a20, 0xc0003e8a20)
2019-11-14T10:17:32.586386+00:00 app[web.1]: /tmp/build_72b16a0659f32d6eae7f03ceab607604/app/cmd/routes.go:37 +0x30a
2019-11-14T10:17:32.586399+00:00 app[web.1]: github.com/getfider/fider/app/cmd.RunServer(0xc00035c080, 0xc00035c080)
2019-11-14T10:17:32.586410+00:00 app[web.1]: /tmp/build_72b16a0659f32d6eae7f03ceab607604/app/cmd/server.go:44 +0x43b
2019-11-14T10:17:32.586417+00:00 app[web.1]: main.main()
2019-11-14T10:17:32.586432+00:00 app[web.1]: /tmp/build_72b16a0659f32d6eae7f03ceab607604/main.go:45 +0x208
2019-11-14T10:17:32.663137+00:00 heroku[web.1]: State changed from starting to crashed
2019-11-14T10:17:32.645505+00:00 heroku[web.1]: Process exited with status 2
```

**Comment by goenning** [comment]
Apparently it did not compile the UI assets, because that step would generate the dist folder. Is that all the logs you’ve got?

**Comment by buremba** [comment]
Yes, it was but I realized that it was a configuration error. We deployed the Fider and already started using it! https://feedback.rakam.io/ Thanks for creating Fider! 🙏

**Comment by pitkes22** [comment]
Gor anyone struggeling with this.. I have skiped adding nodejs buildpackin step in documentation and i wasted like half of day on this 🙁 So make sure you added nodejs buildpack!

**Comment by pitkes22** [comment]
For anyone struggling with this... I have skipped adding nodejs buildpackin step in the documentation and I wasted like half of day on this 🙁 So make sure you added nodejs buildpack!

![image](https://user-images.githubusercontent.com/10003540/74586910-d86b2c80-4fec-11ea-9457-4a8082e0c846.png)
