### ISSUE TITLE
Mage Test Failing -  Windows & Mac

### ISSUE THREAD

**Issue by EtienneBerube** [getfider/fider#841]
I'm trying to get the tests running with `mage test`. I've tried on both Mac and Windows. Each time, I get a lot of errors. I was wondering if this is a known problem? If so, is there a fix for it?

```
Ran all test suites matching /.\\public/i.
?       github.com/getfider/fider       [no test files]
?       github.com/getfider/fider/app   [no test files]
--- FAIL: TestCreateTenant_EmptyToken (0.00s)
panic: could not find handler for 'github.com/getfider/fider/app/models/query.IsSubdomainAvailable'. [recovered]
        panic: could not find handler for 'github.com/getfider/fider/app/models/query.IsSubdomainAvailable'.     

goroutine 111 [running]:
testing.tRunner.func1(0xc000191500)
        c:/go/src/testing/testing.go:874 +0x6a6
panic(0xbb6660, 0xc00006bf30)
        c:/go/src/runtime/panic.go:679 +0x1c0
github.com/getfider/fider/app/pkg/bus.Dispatch(0xd75400, 0xc0000760c0, 0xc00046ddc0, 0x1, 0x1, 0x0, 0x0)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/bus/bus.go:111 +0xa7a
github.com/getfider/fider/app/pkg/validate.Subdomain(0xd75400, 0xc0000760c0, 0xc82c53, 0x7, 0x1, 0x1, 0xc0000d6150, 0xc00017c358, 0xc0000d6150)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/validate/subdomain.go:42 +0x44d
github.com/getfider/fider/app/actions.(*CreateTenant).Validate(0xc00046dee8, 0xd75400, 0xc0000760c0, 0x0, 0x4e221e)
        C:/Users/t-tibrub/Documents/Git/IMP/app/actions/tenant.go:68 +0x292
github.com/getfider/fider/app/actions_test.TestCreateTenant_EmptyToken(0xc000191500)
        C:/Users/t-tibrub/Documents/Git/IMP/app/actions/tenant_test.go:36 +0x12e
testing.tRunner(0xc000191500, 0xcc98a8)
        c:/go/src/testing/testing.go:909 +0x1a1
created by testing.(*T).Run
        c:/go/src/testing/testing.go:960 +0x659
FAIL    github.com/getfider/fider/app/actions   1.480s
--- FAIL: TestGetMainEngine (0.00s)
panic: Path 'dist' not found [recovered]
        panic: Path 'dist' not found

goroutine 24 [running]:
testing.tRunner.func1(0xc00013a800)
        c:/go/src/testing/testing.go:874 +0x6a6
panic(0x113fde0, 0xc00015d9f0)
        c:/go/src/runtime/panic.go:679 +0x1c0
github.com/getfider/fider/app/pkg/web.(*Group).Static(0xc0000a9e70, 0x12e20c8, 0x11, 0x12d5886, 0x4)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/web/engine.go:281 +0x387
github.com/getfider/fider/app/cmd.routes(0xc0000c8d80, 0xc0000c8d80)
        C:/Users/t-tibrub/Documents/Git/IMP/app/cmd/routes.go:37 +0x692
github.com/getfider/fider/app/cmd.TestGetMainEngine(0xc00013a800)
        C:/Users/t-tibrub/Documents/Git/IMP/app/cmd/routes_test.go:13 +0x5f
testing.tRunner(0xc00013a800, 0x133a168)
        c:/go/src/testing/testing.go:909 +0x1a1
created by testing.(*T).Run
        c:/go/src/testing/testing.go:960 +0x659
FAIL    github.com/getfider/fider/app/cmd       1.117s
--- FAIL: TestManageMembersHandler (0.00s)
panic: Error Trace:
- failed to open file: assets.json (app/pkg/web/renderer.go:98)
- open dist/assets.json: The system cannot find the path specified. [recovered]
        panic: Error Trace:
- failed to open file: assets.json (app/pkg/web/renderer.go:98)
- open dist/assets.json: The system cannot find the path specified.

goroutine 8 [running]:
testing.tRunner.func1(0xc000282300)
        c:/go/src/testing/testing.go:874 +0x6a6
panic(0xcf8200, 0xc000004560)
        c:/go/src/runtime/panic.go:679 +0x1c0
github.com/getfider/fider/app/pkg/web.(*Renderer).Render(0xc000028180, 0xeb3b20, 0xc000128ba0, 0xc8, 0xdb38bd, 0xa, 0xdc2b8f, 0x1f, 0x0, 0x0, ...)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/web/renderer.go:153 +0x3262
github.com/getfider/fider/app/pkg/web.(*Context).Render(0xc0002b40e0, 0xc8, 0xdb38bd, 0xa, 0xdc2b8f, 0x1f, 0x0, 0x0, 0xdb8be0, 0x12, ...)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/web/context.go:311 +0x196
github.com/getfider/fider/app/pkg/web.(*Context).Page(0xc0002b40e0, 0xdc2b8f, 0x1f, 0x0, 0x0, 0xdb8be0, 0x12, 0xc000128b70, 0xc0000526b0, 0x1)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/web/context.go:301 +0x2b2
github.com/getfider/fider/app/handlers.ManageMembers.func1(0xc0002b40e0, 0x0, 0x0)
        C:/Users/t-tibrub/Documents/Git/IMP/app/handlers/admin.go:99 +0x29c
github.com/getfider/fider/app/pkg/mock.(*Server).Execute(0xc000128a50, 0xdddd30, 0x403d70, 0xc000235f18)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/mock/server.go:107 +0x11a
github.com/getfider/fider/app/handlers_test.TestManageMembersHandler(0xc000282300)
        C:/Users/t-tibrub/Documents/Git/IMP/app/handlers/admin_test.go:164 +0xd6
testing.tRunner(0xc000282300, 0xdddf68)
        c:/go/src/testing/testing.go:909 +0x1a1
created by testing.(*T).Run
        c:/go/src/testing/testing.go:960 +0x659
FAIL    github.com/getfider/fider/app/handlers  0.946s
--- FAIL: TestAddVoteHandler_InvalidPost (0.00s)
panic: Error Trace:
- failed to open file: assets.json (app/pkg/web/renderer.go:98)
- open dist/assets.json: The system cannot find the path specified. [recovered]
        panic: Error Trace:
- failed to open file: assets.json (app/pkg/web/renderer.go:98)
- open dist/assets.json: The system cannot find the path specified.

goroutine 67 [running]:
testing.tRunner.func1(0xc0003a2200)
        c:/go/src/testing/testing.go:874 +0x6a6
panic(0xc87f80, 0xc000374cc0)
        c:/go/src/runtime/panic.go:679 +0x1c0
github.com/getfider/fider/app/pkg/web.(*Renderer).Render(0xc000163100, 0xe531e0, 0xc0003b8150, 0x194, 0xd3ab04, 0x8, 0xd3ec8d, 0xe, 0xd5b988, 0x45, ...)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/web/renderer.go:153 +0x3262
github.com/getfider/fider/app/pkg/web.(*Context).Render(0xc000196e00, 0x194, 0xd3ab04, 0x8, 0xd3ec8d, 0xe, 0xd5b988, 0x45, 0x0, 0x0, ...)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/web/context.go:311 +0x196
github.com/getfider/fider/app/pkg/web.(*Context).NotFound(...)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/web/context.go:219
github.com/getfider/fider/app/pkg/web.(*Context).Failure(0xc000196e00, 0xe53520, 0xc00006a390, 0x1, 0x1)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/web/context.go:243 +0x733
github.com/getfider/fider/app/handlers/apiv1.addOrRemove(0xc000196e00, 0xd891d0, 0xc000097df8, 0x20106b0)        
        C:/Users/t-tibrub/Documents/Git/IMP/app/handlers/apiv1/post.go:376 +0x3e6
github.com/getfider/fider/app/handlers/apiv1.AddVote.func1(0xc000196e00, 0x12a4820, 0xc000097e78)
        C:/Users/t-tibrub/Documents/Git/IMP/app/handlers/apiv1/post.go:312 +0x4c
github.com/getfider/fider/app/pkg/mock.(*Server).Execute(0xc0003b8090, 0xd891d8, 0xd392d5, 0x6)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/mock/server.go:107 +0x11a
github.com/getfider/fider/app/handlers/apiv1_test.TestAddVoteHandler_InvalidPost(0xc0003a2200)
        C:/Users/t-tibrub/Documents/Git/IMP/app/handlers/apiv1/post_test.go:380 +0x24c
testing.tRunner(0xc0003a2200, 0xd89270)
        c:/go/src/testing/testing.go:909 +0x1a1
created by testing.(*T).Run
        c:/go/src/testing/testing.go:960 +0x659
FAIL    github.com/getfider/fider/app/handlers/apiv1    0.783s
--- FAIL: TestIsAuthorized_WithForbiddenRole (0.00s)
panic: Error Trace:
- failed to open file: assets.json (app/pkg/web/renderer.go:98)
- open dist/assets.json: The system cannot find the path specified. [recovered]
        panic: Error Trace:
- failed to open file: assets.json (app/pkg/web/renderer.go:98)
- open dist/assets.json: The system cannot find the path specified.

goroutine 8 [running]:
testing.tRunner.func1(0xc00016a600)
        c:/go/src/testing/testing.go:874 +0x6a6
panic(0xc4f580, 0xc0000055a0)
        c:/go/src/runtime/panic.go:679 +0x1c0
github.com/getfider/fider/app/pkg/web.(*Renderer).Render(0xc000029b00, 0xdedb20, 0xc00013b7a0, 0x193, 0xcfcb64, 0x8, 0xd00c61, 0xe, 0xd140f9, 0x29, ...)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/web/renderer.go:153 +0x3262
github.com/getfider/fider/app/pkg/web.(*Context).Render(0xc0001c80e0, 0x193, 0xcfcb64, 0x8, 0xd00c61, 0xe, 0xd140f9, 0x29, 0x0, 0x0, ...)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/web/context.go:311 +0x196
github.com/getfider/fider/app/pkg/web.(*Context).Unauthorized(...)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/web/context.go:211
github.com/getfider/fider/app/middlewares.IsAuthorized.func1.1(0xc0001c80e0, 0xc00013b770, 0x0)
        C:/Users/t-tibrub/Documents/Git/IMP/app/middlewares/auth.go:30 +0x2c0
github.com/getfider/fider/app/pkg/mock.(*Server).Execute(0xc00013b710, 0xd26bb8, 0x0, 0x0)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/mock/server.go:107 +0x11a
github.com/getfider/fider/app/middlewares_test.TestIsAuthorized_WithForbiddenRole(0xc00016a600)
        C:/Users/t-tibrub/Documents/Git/IMP/app/middlewares/auth_test.go:31 +0x1ef
testing.tRunner(0xc00016a600, 0xd26bc0)
        c:/go/src/testing/testing.go:909 +0x1a1
created by testing.(*T).Run
        c:/go/src/testing/testing.go:960 +0x659
FAIL    github.com/getfider/fider/app/middlewares       1.287s
?       github.com/getfider/fider/app/models    [no test files]
?       github.com/getfider/fider/app/models/cmd        [no test files]
ok      github.com/getfider/fider/app/models/dto        (cached)
?       github.com/getfider/fider/app/models/enum       [no test files]
?       github.com/getfider/fider/app/models/query      [no test files]
ok      github.com/getfider/fider/app/pkg/assert        (cached)
?       github.com/getfider/fider/app/pkg/backup        [no test files]
ok      github.com/getfider/fider/app/pkg/bus   (cached)
?       github.com/getfider/fider/app/pkg/color [no test files]
ok      github.com/getfider/fider/app/pkg/crypto        (cached)
--- FAIL: TestExportPostsToCSV_Empty (0.00s)
    assert.go:91: Error Trace:
        - app/pkg/csv/csv_test.go:22
        - Equals assertion failed.
         Expected:
                         [[]uint8] [110 117 109 98 101 114 44 116 105 116 108 101 44 100 101 115 99 114 105 112 116 105 111 110 44 99 114 101 97 116 101 100 95 97 116 44 99 114 101 97 116 101 100 95 98 121 44 118 111 116 101 115 95 99 111 117 110 116 44 99 111 109 109 101 110 116 115 95 99 111 117 110 116 44 115 116 97 116 117 115 44 114 101 115 112 111 110 100 101 100 95 98 121 44 114 101 115 112 111 110 100 101 100 95 97 116 44 114 101 115 112 111 110 115 101 44 111 114 105 103 105 110 97 108 95 110 117 109 98 101 114 44 111 114 105 103 105 110 97 108 95 116 105 116 108 101 44 116 97 103 115 13 10]
         Actual:
                         [[]uint8] [110 117 109 98 101 114 44 116 105 116 108 101 44 100 101 115 99 114 105 112 116 105 111 110 44 99 114 101 97 116 101 100 95 97 116 44 99 114 101 97 116 101 100 95 98 121 44 118 111 116 101 115 95 99 111 117 110 116 44 99 111 109 109 101 110 116 115 95 99 111 117 110 116 44 115 116 97 116 117 115 44 114 101 115 112 111 110 100 101 100 95 98 121 44 114 101 115 112 111 110 100 101 100 95 97 116 44 114 101 115 112 111 110 115 101 44 111 114 105 103 105 110 97 108 95 110 117 109 98 101 114 44 111 114 105 103 105 110 97 108 95 116 105 116 108 101 44 116 97 103 115 10]
--- FAIL: TestExportPostsToCSV_OnePost (0.00s)
    assert.go:91: Error Trace:
        - app/pkg/csv/csv_test.go:36
        - Equals assertion failed.
         Expected:
                         [[]uint8] [110 117 109 98 101 114 44 116 105 116 108 101 44 100 101 115 99 114 105 112 116 105 111 110 44 99 114 101 97 116 101 100 95 97 116 44 99 114 101 97 116 101 100 95 98 121 44 118 111 116 101 115 95 99 111 117 110 116 44 99 111 109 109 101 110 116 115 95 99 111 117 110 116 44 115 116 97 116 117 115 44 114 101 115 112 111 110 100 101 100 95 98 121 44 114 101 115 112 111 110 100 101 100 95 97 116 44 114 101 115 112 111 110 115 101 44 111 114 105 103 105 110 97 108 95 110 117 109 98 101 114 44 111 114 105 103 105 110 97 108 95 116 105 116 108 101 44 116 97 103 115 13 10 49 48 44 71 111 32 105 115 32 102 97 115 116 44 86 101 114 121 32 116 105 110 121 32 100 101 115 99 114 105 112 116 105 111 110 44 50 48 49 56 45 48 51 45 50 51 84 49 57 58 51 51 58 50 50 90 44 70 97 99 101 108 101 115 115 44 52 44 50 44 100 101 99 108 105 110 101 100 44 74 111 104 110 32 83 110 
111 119 44 50 48 49 56 45 48 52 45 48 52 84 49 57 58 52 56 58 49 48 90 44 78 111 116 104 105 110 103 32 119 101 32 110 101 101 100 32 116 111 32 100 111 44 44 44 34 101 97 115 121 44 32 105 103 110 111 114 101 100 34 13 10]   
         Actual:
                         [[]uint8] [110 117 109 98 101 114 44 116 105 116 108 101 44 100 101 115 99 114 105 112 116 105 111 110 44 99 114 101 97 116 101 100 95 97 116 44 99 114 101 97 116 101 100 95 98 121 44 118 111 116 101 115 95 99 111 117 110 116 44 99 111 109 109 101 110 116 115 95 99 111 117 110 116 44 115 116 97 116 117 115 44 114 101 115 112 111 110 100 101 100 95 98 121 44 114 101 115 112 111 110 100 101 100 95 97 116 44 114 101 115 112 111 110 115 101 44 111 114 105 103 105 110 97 108 95 110 117 109 98 101 114 44 111 114 105 103 105 110 97 108 95 116 105 116 108 101 44 116 97 103 115 10 49 48 44 71 111 32 105 115 32 102 97 115 116 44 86 101 114 121 32 116 105 
110 121 32 100 101 115 99 114 105 112 116 105 111 110 44 50 48 49 56 45 48 51 45 50 51 84 49 57 58 51 51 58 50 50 90 44 70 97 99 101 108 101 115 115 44 52 44 50 44 100 101 99 108 105 110 101 100 44 74 111 104 110 32 83 110 111 119 44 50 48 49 56 45 48 52 45 48 52 84 49 57 58 52 56 58 49 48 90 44 78 111 116 104 105 110 103 32 119 101 32 110 101 101 100 32 116 111 32 100 111 44 44 44 34 101 97 115 121 44 32 105 103 110 111 114 101 100 34 10]
--- FAIL: TestExportPostsToCSV_MorePosts (0.00s)
    assert.go:91: Error Trace:
        - app/pkg/csv/csv_test.go:52
        - Equals assertion failed.
         Expected:
                         [[]uint8] [110 117 109 98 101 114 44 116 105 116 108 101 44 100 101 115 99 114 105 112 116 105 111 110 44 99 114 101 97 116 101 100 95 97 116 44 99 114 101 97 116 101 100 95 98 121 44 118 111 116 101 115 95 99 111 117 110 116 44 99 111 109 109 101 110 116 115 95 99 111 117 110 116 44 115 116 97 116 117 115 44 114 101 115 112 111 110 100 101 100 95 98 121 44 114 101 115 112 111 110 100 101 100 95 97 116 44 114 101 115 112 111 110 115 101 44 111 114 105 103 105 110 97 108 95 110 117 109 98 101 114 44 111 114 105 103 105 110 97 108 95 116 105 116 108 101 44 116 97 103 115 13 10 49 48 44 71 111 32 105 115 32 102 97 115 116 44 86 101 114 121 32 116 105 110 121 32 100 101 115 99 114 105 112 116 105 111 110 44 50 48 49 56 45 48 51 45 50 51 84 49 57 58 51 51 58 50 50 90 44 70 97 99 101 108 101 115 115 44 52 44 50 44 100 101 99 108 105 110 101 100 44 74 111 104 110 32 83 110 
111 119 44 50 48 49 56 45 48 52 45 48 52 84 49 57 58 52 56 58 49 48 90 44 78 111 116 104 105 110 103 32 119 101 32 110 101 101 100 32 116 111 32 100 111 44 44 44 34 101 97 115 121 44 32 105 103 110 111 114 101 100 34 13 10 49 
53 44 71 111 32 105 115 32 103 114 101 97 116 44 44 50 48 49 56 45 48 50 45 50 49 84 49 53 58 53 49 58 51 53 90 44 83 111 109 101 111 110 101 32 101 108 115 101 44 52 44 50 44 111 112 101 110 44 44 44 44 44 44 13 10 50 48 44 71 111 32 105 115 32 101 97 115 121 44 44 50 48 49 56 45 48 49 45 49 50 84 48 49 58 52 54 58 53 57 90 44 70 97 99 
101 108 101 115 115 44 52 44 50 44 100 117 112 108 105 99 97 116 101 44 65 114 121 97 32 83 116 97 114 107 44 50 
48 49 56 45 48 51 45 49 55 84 49 48 58 49 53 58 52 50 90 44 84 104 105 115 32 104 97 115 32 97 108 114 101 97 100 121 32 98 101 101 110 32 115 117 103 103 101 115 116 101 100 44 57 57 44 71 111 32 105 115 32 118 101 114 121 32 101 97 115 121 44 34 116 104 105 115 45 116 97 103 45 104 97 115 44 99 111 109 109 97 34 13 10]
         Actual:
                         [[]uint8] [110 117 109 98 101 114 44 116 105 116 108 101 44 100 101 115 99 114 105 112 116 105 111 110 44 99 114 101 97 116 101 100 95 97 116 44 99 114 101 97 116 101 100 95 98 121 44 118 111 116 101 115 95 99 111 117 110 116 44 99 111 109 109 101 110 116 115 95 99 111 117 110 116 44 115 116 97 116 117 115 44 114 101 115 112 111 110 100 101 100 95 98 121 44 114 101 115 112 111 110 100 101 100 95 97 116 44 114 101 115 112 111 110 115 101 44 111 114 105 103 105 110 97 108 95 110 117 109 98 101 114 44 111 114 105 103 105 110 97 108 95 116 105 116 108 101 44 116 97 103 115 10 49 48 44 71 111 32 105 115 32 102 97 115 116 44 86 101 114 121 32 116 105 
110 121 32 100 101 115 99 114 105 112 116 105 111 110 44 50 48 49 56 45 48 51 45 50 51 84 49 57 58 51 51 58 50 50 90 44 70 97 99 101 108 101 115 115 44 52 44 50 44 100 101 99 108 105 110 101 100 44 74 111 104 110 32 83 110 111 119 44 50 48 49 56 45 48 52 45 48 52 84 49 57 58 52 56 58 49 48 90 44 78 111 116 104 105 110 103 32 119 101 32 110 101 101 100 32 116 111 32 100 111 44 44 44 34 101 97 115 121 44 32 105 103 110 111 114 101 100 34 10 49 53 44 
71 111 32 105 115 32 103 114 101 97 116 44 44 50 48 49 56 45 48 50 45 50 49 84 49 53 58 53 49 58 51 53 90 44 83 111 109 101 111 110 101 32 101 108 115 101 44 52 44 50 44 111 112 101 110 44 44 44 44 44 44 10 50 48 44 71 111 32 
105 115 32 101 97 115 121 44 44 50 48 49 56 45 48 49 45 49 50 84 48 49 58 52 54 58 53 57 90 44 70 97 99 101 108 101 115 115 44 52 44 50 44 100 117 112 108 105 99 97 116 101 44 65 114 121 97 32 83 116 97 114 107 44 50 48 49 56 
45 48 51 45 49 55 84 49 48 58 49 53 58 52 50 90 44 84 104 105 115 32 104 97 115 32 97 108 114 101 97 100 121 32 98 101 101 110 32 115 117 103 103 101 115 116 101 100 44 57 57 44 71 111 32 105 115 32 118 101 114 121 32 101 97 115 121 44 34 116 104 105 115 45 116 97 103 45 104 97 115 44 99 111 109 109 97 34 10]
FAIL
FAIL    github.com/getfider/fider/app/pkg/csv   1.149s
--- FAIL: TestBind_SimpleStruct (0.03s)
    assert.go:151: Error Trace:
        - app/pkg/dbx/dbx_test.go:52
        - IsNil assertion failed.
         Actual:
                         Object not found
    assert.go:91: Error Trace:
        - app/pkg/dbx/dbx_test.go:53
        - Equals assertion failed.
         Expected:
                         [int] 1
         Actual:
                         [int] 0
    assert.go:91: Error Trace:
        - app/pkg/dbx/dbx_test.go:54
        - Equals assertion failed.
         Expected:
                         [string] Jon Snow
         Actual:
                         [string]
--- FAIL: TestBind_DeepNestedStruct (0.01s)
    assert.go:151: Error Trace:
        - app/pkg/dbx/dbx_test.go:72
        - IsNil assertion failed.
         Actual:
                         Object not found
    assert.go:91: Error Trace:
        - app/pkg/dbx/dbx_test.go:73
        - Equals assertion failed.
         Expected:
                         [string] facebook
         Actual:
                         [string]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x8934cc]

goroutine 8 [running]:
testing.tRunner.func1(0xc0000fc200)
        c:/go/src/testing/testing.go:874 +0x6a6
panic(0x8f43e0, 0xc46b90)
        c:/go/src/runtime/panic.go:679 +0x1c0
github.com/getfider/fider/app/pkg/dbx_test.TestBind_DeepNestedStruct(0xc0000fc200)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/dbx/dbx_test.go:74 +0x2bc
testing.tRunner(0xc0000fc200, 0x968218)
        c:/go/src/testing/testing.go:909 +0x1a1
created by testing.(*T).Run
        c:/go/src/testing/testing.go:960 +0x659
FAIL    github.com/getfider/fider/app/pkg/dbx   1.024s
--- FAIL: TestHasLegal (0.00s)
    assert.go:91: Error Trace:
        - app/pkg/assert/assert.go:117
        - Equals assertion failed.
         Expected:
                         [bool] true
         Actual:
                         [bool] false
--- FAIL: TestMultiTenantDomain (0.00s)
    assert.go:91: Error Trace:
        - app/pkg/env/env_test.go:46
        - Equals assertion failed.
         Expected:
                         [string] .test.fider.io
         Actual:
                         [string]
    assert.go:91: Error Trace:
        - app/pkg/env/env_test.go:48
        - Equals assertion failed.
         Expected:
                         [string] .dev.fider.io
         Actual:
                         [string]
    assert.go:91: Error Trace:
        - app/pkg/env/env_test.go:50
        - Equals assertion failed.
         Expected:
                         [string] .fider.io
         Actual:
                         [string]
--- FAIL: TestSubdomain (0.00s)
    assert.go:91: Error Trace:
        - app/pkg/env/env_test.go:70
        - Equals assertion failed.
         Expected:
                         [string] demo
         Actual:
                         [string]
    assert.go:91: Error Trace:
        - app/pkg/env/env_test.go:71
        - Equals assertion failed.
         Expected:
                         [string] demo
         Actual:
                         [string]
FAIL
FAIL    github.com/getfider/fider/app/pkg/env   0.384s
ok      github.com/getfider/fider/app/pkg/errors        (cached)
ok      github.com/getfider/fider/app/pkg/jsonq (cached)
ok      github.com/getfider/fider/app/pkg/jwt   (cached)
ok      github.com/getfider/fider/app/pkg/log   (cached)
ok      github.com/getfider/fider/app/pkg/markdown      (cached)
?       github.com/getfider/fider/app/pkg/mock  [no test files]
ok      github.com/getfider/fider/app/pkg/rand  (cached)
--- FAIL: TestInvalidCNAME (0.00s)
panic: could not find handler for 'github.com/getfider/fider/app/models/query.IsCNAMEAvailable'. [recovered]     
        panic: could not find handler for 'github.com/getfider/fider/app/models/query.IsCNAMEAvailable'.

goroutine 21 [running]:
testing.tRunner.func1(0xc000158300)
        c:/go/src/testing/testing.go:874 +0x6a6
panic(0x788f60, 0xc000138c40)
        c:/go/src/runtime/panic.go:679 +0x1c0
github.com/getfider/fider/app/pkg/bus.Dispatch(0x82d520, 0xc0000120e8, 0xc000075e08, 0x1, 0x1, 0x0, 0x0)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/bus/bus.go:111 +0xa7a
github.com/getfider/fider/app/pkg/bus.MustDispatch(...)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/bus/bus.go:87
github.com/getfider/fider/app/pkg/validate.CNAME(0x82d520, 0xc0000120e8, 0x7d6554, 0x16, 0xc000138c20, 0x1, 0x1) 
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/validate/general.go:70 +0x417
github.com/getfider/fider/app/pkg/validate_test.TestInvalidCNAME(0xc000158300)
        C:/Users/t-tibrub/Documents/Git/IMP/app/pkg/validate/general_test.go:88 +0xf8
testing.tRunner(0xc000158300, 0x7e0fe8)
        c:/go/src/testing/testing.go:909 +0x1a1
created by testing.(*T).Run
        c:/go/src/testing/testing.go:960 +0x659
FAIL    github.com/getfider/fider/app/pkg/validate      0.415s
```

Some of these errors look like normal failing unit tests. However, some say: `dist folder not found`, which becomes a bit more problematic.

**Comment by EtienneBerube** [comment]
Update: There were a couple of test environments that were wrong. When reviewing the test environment, there were some differences that I did not catch.

**Comment by leonardo2204** [comment]
@EtienneBerube I know this is kinda old, but do you mind sharing how your config ended up? I'm facing a similar problem here. 
Thanks!
