### ISSUE TITLE
panic: Path 'dist' not found

### ISSUE THREAD

**Issue by Sam512** [getfider/fider#857]
When deploying to Heroku I get this error in the logs

`2020-05-01T10:10:31.166639+00:00 heroku[web.1]: State changed from crashed to starting
2020-05-01T10:10:34.136788+00:00 heroku[web.1]: State changed from starting to crashed
2020-05-01T10:10:33.807938+00:00 app[web.1]: [1m[34mINFO[0m[0m [2020-05-01T10:10:33Z] [MIGRATE] [RdfeIG1OfhMc5zmEYPZq0e3TqCy8qmJS] Running migrations...
2020-05-01T10:10:33.808455+00:00 app[web.1]: [1m[34mINFO[0m[0m [2020-05-01T10:10:33Z] [MIGRATE] [RdfeIG1OfhMc5zmEYPZq0e3TqCy8qmJS] Found total of 63 migration files.
2020-05-01T10:10:33.905924+00:00 app[web.1]: [1m[34mINFO[0m[0m [2020-05-01T10:10:33Z] [MIGRATE] [RdfeIG1OfhMc5zmEYPZq0e3TqCy8qmJS] Current version is 201904091921
2020-05-01T10:10:33.905994+00:00 app[web.1]: [1m[34mINFO[0m[0m [2020-05-01T10:10:33Z] [MIGRATE] [RdfeIG1OfhMc5zmEYPZq0e3TqCy8qmJS] Migrations are already up to date.
2020-05-01T10:10:34.054050+00:00 app[web.1]: panic: Path 'dist' not found
2020-05-01T10:10:34.054055+00:00 app[web.1]: 
2020-05-01T10:10:34.054059+00:00 app[web.1]: goroutine 1 [running]:
2020-05-01T10:10:34.054158+00:00 app[web.1]: github.com/getfider/fider/app/pkg/web.(*Group).Static(0xc000377cf0, 0xe24275, 0x11, 0xe181a5, 0x4)
2020-05-01T10:10:34.054185+00:00 app[web.1]: 	/tmp/build_910bea6d0c09a35bf9ac8e2179060c9a/app/pkg/web/engine.go:281 +0x283
2020-05-01T10:10:34.054189+00:00 app[web.1]: github.com/getfider/fider/app/cmd.routes(0xc00040aa20, 0xc00040aa20)
2020-05-01T10:10:34.054242+00:00 app[web.1]: 	/tmp/build_910bea6d0c09a35bf9ac8e2179060c9a/app/cmd/routes.go:37 +0x30a
2020-05-01T10:10:34.054263+00:00 app[web.1]: github.com/getfider/fider/app/cmd.RunServer(0xc000288200, 0xc000288200)
2020-05-01T10:10:34.054297+00:00 app[web.1]: 	/tmp/build_910bea6d0c09a35bf9ac8e2179060c9a/app/cmd/server.go:44 +0x43b
2020-05-01T10:10:34.054314+00:00 app[web.1]: main.main()
2020-05-01T10:10:34.054342+00:00 app[web.1]: 	/tmp/build_910bea6d0c09a35bf9ac8e2179060c9a/main.go:45 +0x208`

I followed the guide here: https://getfider.com/docs/hosting-on-heroku/

Any help is appreciated.

**Comment by Sam512** [comment]
Closed because I realized I forgot to install the Node.js buildpack. 👀
