### ISSUE TITLE
Heroku: Application error

### ISSUE THREAD

**Issue by moevbiz** [getfider/fider#907]
I've followed the exact steps on https://getfider.com/docs/hosting-on-heroku/, setting up gmail's smtp servers as a free smtp solution. It builds correctly, but I'm getting the "Application error" page. 

The logs show the following:

```
2021-02-22T20:38:46.987376+00:00 app[web.1]: 	/tmp/build_f462037c_/app/pkg/env/env.go:107 +0x1de
2021-02-22T20:38:46.987377+00:00 app[web.1]: github.com/getfider/fider/app/pkg/env.init.0()
2021-02-22T20:38:46.987397+00:00 app[web.1]: 	/tmp/build_f462037c_/app/pkg/env/env.go:99 +0x20
2021-02-22T20:38:47.034165+00:00 heroku[web.1]: Process exited with status 2
2021-02-22T20:38:47.092058+00:00 heroku[web.1]: State changed from starting to crashed
2021-02-22T20:38:48.481715+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=index-fider.herokuapp.com request_id=5c9f8ca1-a5fc-40b8-8b1f-d4a6423c76f6 fwd="194.118.247.206" dyno= connect= service= status=503 bytes= protocol=https
2021-02-22T20:38:48.552226+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=index-fider.herokuapp.com request_id=0e55f009-6255-4c58-a03d-179173295393 fwd="194.118.247.206" dyno= connect= service= status=503 bytes= protocol=https
2021-02-22T20:40:10.000000+00:00 app[api]: Build succeeded
2021-02-22T20:40:27.269823+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=index-fider.herokuapp.com request_id=fb38983d-3fdf-4ab3-bcd6-6decddeddcd2 fwd="194.118.247.206" dyno= connect= service= status=503 bytes= protocol=https
2021-02-22T20:49:52.625936+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=index-fider.herokuapp.com request_id=f633931f-44f1-446b-8b0c-f33151479dc9 fwd="194.118.247.206" dyno= connect= service= status=503 bytes= protocol=https
```

Any idea what might be the cause of this issue? Looks like some environment variable might be missing…

**Comment by moevbiz** [comment]
Some time later, without touching anything, it is giving me the following:

```
2021-02-22T21:02:58.567240+00:00 heroku[web.1]: State changed from crashed to starting
2021-02-22T21:03:02.272288+00:00 heroku[web.1]: Starting process with command `./bin/fider migrate && ./bin/fider`
2021-02-22T21:03:05.600716+00:00 heroku[web.1]: Process exited with status 2
2021-02-22T21:03:05.664972+00:00 heroku[web.1]: State changed from starting to crashed
2021-02-22T21:03:05.482508+00:00 app[web.1]: panic: Error Trace: 
2021-02-22T21:03:05.482543+00:00 app[web.1]: - failed to parse environment variables (app/pkg/env/env.go:107)
2021-02-22T21:03:05.482574+00:00 app[web.1]: - the environment variable "HOST_DOMAIN" is missing
2021-02-22T21:03:05.482594+00:00 app[web.1]: 
2021-02-22T21:03:05.482676+00:00 app[web.1]: goroutine 1 [running]:
2021-02-22T21:03:05.482768+00:00 app[web.1]: github.com/getfider/fider/app/pkg/env.Reload()
2021-02-22T21:03:05.482868+00:00 app[web.1]: 	/tmp/build_f462037c_/app/pkg/env/env.go:107 +0x1de
2021-02-22T21:03:05.482913+00:00 app[web.1]: github.com/getfider/fider/app/pkg/env.init.0()
2021-02-22T21:03:05.483015+00:00 app[web.1]: 	/tmp/build_f462037c_/app/pkg/env/env.go:99 +0x20
2021-02-22T21:05:50.574466+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=index-fider.herokuapp.com request_id=848edd4a-da1b-4313-bcf6-12d957b268a3 fwd="194.118.247.206" dyno= connect= service= status=503 bytes= protocol=https
```

what is `HOST_DOMAIN`?

**Comment by moevbiz** [comment]
I manually set `HOST_DOMAIN` to the domain that Heroku assigned to my instance… It looks like it's working now, at least I can enter name and email address. But the confirmation mail is not being sent. That's probably a different issue though.

**Comment by moevbiz** [comment]
Ok, no, that wasn't right. I tried with Mailgun instead of google smtp. The email is delivered properly, but when I click on the activation link, fider says: "PAGE NOT FOUND – The link you clicked may be broken or the page may have been removed."

If I just go to the index page, it says the same.

**Comment by moevbiz** [comment]
Finally figured it out and feel stupid now – it's simply the Heroku assigned domain (`your-instance.herokuapp.com`) without any protocols etc...

**Comment by mipapo** [comment]
So everythings fine now? You could close this issue then :)

**Comment by moevbiz** [comment]
True. Closing this issue and will create a new one about the incomplete docs :~)

**Comment by echan00** [comment]
Followed the Heroku installation docs and am running into an Application error problem.

Does this look correct? It doesn't for me..

My ENV
```
BASE_URL: https://swapboxfeedback.herokuapp.com
HOST_DOMAIN: swapboxfeedback.herokuapp.com
```

**Comment by echan00** [comment]
Got it to work, only use BASE_URL. NOT both HOST_DOMAIN and BASE_URL :)
