### ISSUE TITLE
Why the changes to the docker documentation?

### ISSUE THREAD

**Issue by StrangeRanger** [getfider/fider#927]
I recently went back to the Fider documentation, specifically the docker documentation, and it seems like y'all made changes to it. But why was it changed to contain less informative and helpful information. Now there is nothing mentioning setting up fider with a database outside of the docker image, and so on and so forth. Why were these changes made?

Before:

![screencapture-web-archive-org-web-20200810054047-https-getfider-com-docs-hosting-instance-2021-03-22-14_35_12](https://user-images.githubusercontent.com/30395560/112062006-8b755600-8b1c-11eb-8916-005309edf5e9.png)

After:

![screencapture-getfider-docs-hosting-instance-2021-03-22-14_36_07](https://user-images.githubusercontent.com/30395560/112062010-8ca68300-8b1c-11eb-9257-4b172574319e.png)

**Comment by goenning** [comment]
The initial docs had Postgres inside the compose running as a container, but strong recommendation to host Postgres outside.

There is not argue that having both inside a container does simplify a lot the installation process. Looking back now (and also checking how Discourse does it), it might not be that big of a problem having Postgres in a container, as long as the volumes are mapped to the host.

The intention was to simplify, but I might have caused more problems. What you think? I’m ok adding Postgres back to Docker compose and NOT having any comments on hosting it outside. Would that make it better?

**Comment by StrangeRanger** [comment]
I've also noticed a bug with the configurations in the docs for the docker. For `ports`, one of the "3000" causes an error to be produced. Removing one of them so that is looks like the code below, solves the problems.

```docker
    ports:
      - "3000"
```

This is the error code produced:
```
Recreating fider_app_1 ... 

ERROR: for fider_app_1  a bytes-like object is required, not 'str'

ERROR: for app  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/4fd8f4fd432a7e3141a5da35a36fdcad0546e0df3eea283e1a128ae6da10dfe3/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/compose/service.py", line 625, in start_container
    container.start()
  File "/usr/lib/python3/dist-packages/compose/container.py", line 241, in start
    return self.client.start(self.id, **options)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint fider_app_1 (f9bb469bbea55510bd894fffba7d28322c04ec47a16a81d180cabd29b7e6061c): Error starting userland proxy: listen tcp4 0.0.0.0:3000: bind: address already in use'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 565, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 548, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 561, in execute_convergence_plan
    return self._execute_convergence_recreate(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 486, in _execute_convergence_recreate
    containers, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 481, in recreate
    return self.recreate_container(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 602, in recreate_container
    self.start_container(new_container)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 627, in start_container
    if "driver failed programming external connectivity" in ex.explanation:
TypeError: a bytes-like object is required, not 'str'
```

**Comment by goenning** [comment]
I've updated the docs to be similar to how it was before.

I think 3000:3000 is correct, maybe you are using compose v3?

**Comment by StrangeRanger** [comment]
@goenning

```bash
❯ docker-compose --version
docker-compose version 1.25.0, build unknown
```

Looks like I'm running 1.25.0. Should I be running a different version?

**Comment by StrangeRanger** [comment]
And thank you for making those modifications to the docs. It makes it much easier, at least in my opinion.
