### ISSUE TITLE
Cannot find module 'mini-css-extract-plugin'

### ISSUE THREAD

**Issue by ItsMrReals** [getfider/fider#928]
I am getting this issue when I try to deploy on heroku
```
       Running heroku-postbuild

       

       > fider@0.0.0 heroku-postbuild

       > NODE_ENV=production npx webpack-cli

       

[webpack-cli] Failed to load '/tmp/build_d5f8dc0a/webpack.config.js' config

[webpack-cli] Error: Cannot find module 'mini-css-extract-plugin'

Require stack:

- /tmp/build_d5f8dc0a/webpack.config.js

- /tmp/npmcache.eWhNC/_npx/73f0de3f6fbaf968/node_modules/webpack-cli/lib/webpack-cli.js

- /tmp/npmcache.eWhNC/_npx/73f0de3f6fbaf968/node_modules/webpack-cli/lib/bootstrap.js

- /tmp/npmcache.eWhNC/_npx/73f0de3f6fbaf968/node_modules/webpack-cli/bin/cli.js

    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)

    at Function.Module._load (node:internal/modules/cjs/loader:769:27)

    at Module.require (node:internal/modules/cjs/loader:996:19)

    at require (/tmp/npmcache.eWhNC/_npx/73f0de3f6fbaf968/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)

    at Object.<anonymous> (/tmp/build_d5f8dc0a/webpack.config.js:3:30)

    at Module._compile (/tmp/npmcache.eWhNC/_npx/73f0de3f6fbaf968/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)

    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)

    at Module.load (node:internal/modules/cjs/loader:972:32)

    at Function.Module._load (node:internal/modules/cjs/loader:813:14)

    at Module.require (node:internal/modules/cjs/loader:996:19) {

  code: 'MODULE_NOT_FOUND',

  requireStack: [

    '/tmp/build_d5f8dc0a/webpack.config.js',

    '/tmp/npmcache.eWhNC/_npx/73f0de3f6fbaf968/node_modules/webpack-cli/lib/webpack-cli.js',

    '/tmp/npmcache.eWhNC/_npx/73f0de3f6fbaf968/node_modules/webpack-cli/lib/bootstrap.js',

    '/tmp/npmcache.eWhNC/_npx/73f0de3f6fbaf968/node_modules/webpack-cli/bin/cli.js'

  ]

}
```

**Comment by goenning** [comment]
did you add nodejs buildpack?

**Comment by ItsMrReals** [comment]
How?

**Comment by goenning** [comment]
https://getfider.com/docs/hosting-on-heroku

**Comment by ItsMrReals** [comment]
Yes, I did, I still get the issue

**Comment by goenning** [comment]
can you post the full log and which repo did you link to Heroku?
