### ISSUE TITLE
[BUG] failed to send email with template signup_email

### ISSUE THREAD

**Issue by masteradit** [getfider/fider#943]
I am hosting Fider on Heroku (`main` branch `6fc05d4fd3a8048a8f947a11a6c2ae8346dc23a0` commit).

I followed all the steps given here: https://getfider.com/docs/hosting-on-heroku
When it was deployed and I opened the web page, I was redirected to the sign up form. I filled the form, but I never got the verification email. Here's the output in Application Logs:

```
2021-04-13T10:52:41.920000+00:00 app[web.1]: github.com/getfider/fider/app/middlewares.WorkerSetup.func1.1(0xc0003829c0, 0x0, 0x0)
2021-04-13T10:52:41.920000+00:00 app[web.1]: 	/tmp/build_31fcb11b/app/middlewares/setup.go:51 +0x602
2021-04-13T10:52:41.920001+00:00 app[web.1]: github.com/getfider/fider/app/pkg/worker.(*BackgroundWorker).Run(0xc0001a4200, 0x1b1e545, 0x1)
2021-04-13T10:52:41.920001+00:00 app[web.1]: 	/tmp/build_31fcb11b/app/pkg/worker/worker.go:73 +0x26c
2021-04-13T10:52:41.920002+00:00 app[web.1]: created by github.com/getfider/fider/app/pkg/web.(*Engine).Start
2021-04-13T10:52:41.920002+00:00 app[web.1]: 	/tmp/build_31fcb11b/app/pkg/web/engine.go:124 +0x525
2021-04-13T10:52:41.920003+00:00 app[web.1]:  (app/pkg/errors/errors.go:40)
2021-04-13T10:52:41.920003+00:00 app[web.1]: - github.com/getfider/fider/app/services/email/smtp.sendMail:94 (app/pkg/errors/errors.go:39)
2021-04-13T10:52:41.920004+00:00 app[web.1]: - failed to send email with template signup_email (app/services/email/smtp/smtp.go:94)
2021-04-13T10:52:41.920004+00:00 app[web.1]: - EOF
```

**Comment by Prophet-Phoenix** [comment]
I got the exact same error, also when setting up my instance and wating for verification mail. The only difference is, i followed the given documentation for the setup with docker-compose on my debian vps. Am happy to provide more info, if you say what.

**Comment by goenning** [comment]
> Maybe the log should provide more info why sendmail failed?

Yeah. So somewhere in Go stdlib, we got an EOF. It doesn't say anything more than that. We could decorate the smtp.go with more details, but it would just tell us which function failed. But that's better than nothing and it might help us find the root cause.

**Comment by Prophet-Phoenix** [comment]
I just tested again with starttls since i found out that my host still does support it - and success.

Could it be the
`EMAIL_SMTP_ENABLE_STARTTLS: 'false'`
argument does not get recognized by the app in the docker install?

Yesterday i read something about compose files not parsing boolean veriables since they are YAML. Could that cause the problem with (not) disabling STARTTLS?

**Comment by masteradit** [comment]
I tried running Fider again from the `main` branch `1cda857a` commit. This is the error I got in Application Logs:

```
2021-05-14T18:12:44.878799+00:00 app[web.1]: [1m[34mINFO[0m[0m [2021-05-14T18:12:44Z] [BGW] [cInfPLZ3RNZYJSeOY0LfIctPwqls5uUE] Task '[36mSend sign up email[0m' started on worker '[36m11[0m'
2021-05-14T18:12:44.893979+00:00 heroku[router]: at=info method=POST path="/_api/tenants" host=fider-testing.herokuapp.com request_id=ec304da1-9d2c-4bda-884d-f1ba93c1eeca fwd="49.36.247.38" dyno=web.1 connect=6ms service=169ms status=200 bytes=735 protocol=https
2021-05-14T18:14:02.292844+00:00 app[web.1]: [1m[31mERROR[0m[0m [2021-05-14T18:14:02Z] [BGW] [cInfPLZ3RNZYJSeOY0LfIctPwqls5uUE] Error Trace: 
2021-05-14T18:14:02.292865+00:00 app[web.1]: - app/middlewares/setup.go:51
2021-05-14T18:14:02.292866+00:00 app[web.1]: - goroutine 80 [running]:
2021-05-14T18:14:02.292866+00:00 app[web.1]: runtime/debug.Stack(0x1c965a0, 0xc00014e3a0, 0x0)
2021-05-14T18:14:02.292868+00:00 app[web.1]: 	/tmp/codon/tmp/cache/go1.16.1/go/src/runtime/debug/stack.go:24 +0x9f
2021-05-14T18:14:02.292868+00:00 app[web.1]: github.com/getfider/fider/app/pkg/errors.Panicked(0x1a33560, 0xc00014e3a0, 0xc00014e3a0, 0xc0002073d0)
2021-05-14T18:14:02.292869+00:00 app[web.1]: 	/tmp/build_815585c8/app/pkg/errors/errors.go:40 +0xe9
2021-05-14T18:14:02.292869+00:00 app[web.1]: github.com/getfider/fider/app/middlewares.WorkerSetup.func1.1.2(0xc000412570, 0xc0002886a8, 0xc000207e88)
2021-05-14T18:14:02.292869+00:00 app[web.1]: 	/tmp/build_815585c8/app/middlewares/setup.go:51 +0x5a
2021-05-14T18:14:02.292870+00:00 app[web.1]: panic(0x1a33560, 0xc00014e3a0)
2021-05-14T18:14:02.292871+00:00 app[web.1]: 	/tmp/codon/tmp/cache/go1.16.1/go/src/runtime/panic.go:965 +0x1b9
2021-05-14T18:14:02.292871+00:00 app[web.1]: github.com/getfider/fider/app/services/email/smtp.sendMail(0x1ca4a30, 0xc000412570, 0xc0001d4d80)
2021-05-14T18:14:02.292871+00:00 app[web.1]: 	/tmp/build_815585c8/app/services/email/smtp/smtp.go:94 +0x180e
2021-05-14T18:14:02.292872+00:00 app[web.1]: reflect.Value.call(0x1a1bb00, 0x1b64918, 0x13, 0x1afd2b6, 0x4, 0xc000207ca0, 0x2, 0x2, 0x19c3668, 0x8, ...)
2021-05-14T18:14:02.292872+00:00 app[web.1]: 	/tmp/codon/tmp/cache/go1.16.1/go/src/reflect/value.go:476 +0x8e7
2021-05-14T18:14:02.292872+00:00 app[web.1]: reflect.Value.Call(0x1a1bb00, 0x1b64918, 0x13, 0xc000207ca0, 0x2, 0x2, 0x85f9f3, 0x1a0ed60, 0x203000)
2021-05-14T18:14:02.292873+00:00 app[web.1]: 	/tmp/codon/tmp/cache/go1.16.1/go/src/reflect/value.go:337 +0xb9
2021-05-14T18:14:02.292873+00:00 app[web.1]: github.com/getfider/fider/app/pkg/bus.Publish(0x1ca4a30, 0xc000412570, 0xc000207d78, 0x1, 0x1)
2021-05-14T18:14:02.292874+00:00 app[web.1]: 	/tmp/build_815585c8/app/pkg/bus/bus.go:152 +0x439
2021-05-14T18:14:02.292874+00:00 app[web.1]: github.com/getfider/fider/app/tasks.SendSignUpEmail.func1(0xc000412570, 0xc000412480, 0x1a0ed60)
2021-05-14T18:14:02.292875+00:00 app[web.1]: 	/tmp/build_815585c8/app/tasks/tasks.go:41 +0x3c7
2021-05-14T18:14:02.292875+00:00 app[web.1]: github.com/getfider/fider/app/middlewares.WorkerSetup.func1.1(0xc000412570, 0x0, 0x0)
2021-05-14T18:14:02.292875+00:00 app[web.1]: 	/tmp/build_815585c8/app/middlewares/setup.go:58 +0x422
2021-05-14T18:14:02.292876+00:00 app[web.1]: github.com/getfider/fider/app/pkg/worker.(*BackgroundWorker).Run(0xc0001d4180, 0x1b34425, 0x2)
2021-05-14T18:14:02.292876+00:00 app[web.1]: 	/tmp/build_815585c8/app/pkg/worker/worker.go:73 +0x26c
2021-05-14T18:14:02.292876+00:00 app[web.1]: created by github.com/getfider/fider/app/pkg/web.(*Engine).Start
2021-05-14T18:14:02.292877+00:00 app[web.1]: 	/tmp/build_815585c8/app/pkg/web/engine.go:125 +0x525
2021-05-14T18:14:02.292877+00:00 app[web.1]:  (app/pkg/errors/errors.go:40)
2021-05-14T18:14:02.292878+00:00 app[web.1]: - github.com/getfider/fider/app/services/email/smtp.sendMail:94 (app/pkg/errors/errors.go:39)
2021-05-14T18:14:02.292878+00:00 app[web.1]: - failed to send email with template signup_email (app/services/email/smtp/smtp.go:94)
2021-05-14T18:14:02.292878+00:00 app[web.1]: - EOF
2021-05-14T18:14:02.308049+00:00 app[web.1]: [1m[31mERROR[0m[0m [2021-05-14T18:14:02Z] [BGW] [cInfPLZ3RNZYJSeOY0LfIctPwqls5uUE] Error Trace: 
2021-05-14T18:14:02.308051+00:00 app[web.1]: - app/middlewares/setup.go:51
2021-05-14T18:14:02.308051+00:00 app[web.1]: - goroutine 80 [running]:
2021-05-14T18:14:02.308052+00:00 app[web.1]: runtime/debug.Stack(0x1c965a0, 0xc00014e3a0, 0x0)
2021-05-14T18:14:02.308053+00:00 app[web.1]: 	/tmp/codon/tmp/cache/go1.16.1/go/src/runtime/debug/stack.go:24 +0x9f
2021-05-14T18:14:02.308053+00:00 app[web.1]: github.com/getfider/fider/app/pkg/errors.Panicked(0x1a33560, 0xc00014e3a0, 0xc00014e3a0, 0xc0002073d0)
2021-05-14T18:14:02.308053+00:00 app[web.1]: 	/tmp/build_815585c8/app/pkg/errors/errors.go:40 +0xe9
2021-05-14T18:14:02.308054+00:00 app[web.1]: github.com/getfider/fider/app/middlewares.WorkerSetup.func1.1.2(0xc000412570, 0xc0002886a8, 0xc000207e88)
2021-05-14T18:14:02.308054+00:00 app[web.1]: 	/tmp/build_815585c8/app/middlewares/setup.go:51 +0x5a
2021-05-14T18:14:02.308055+00:00 app[web.1]: panic(0x1a33560, 0xc00014e3a0)
2021-05-14T18:14:02.308055+00:00 app[web.1]: 	/tmp/codon/tmp/cache/go1.16.1/go/src/runtime/panic.go:965 +0x1b9
2021-05-14T18:14:02.308055+00:00 app[web.1]: github.com/getfider/fider/app/services/email/smtp.sendMail(0x1ca4a30, 0xc000412570, 0xc0001d4d80)
2021-05-14T18:14:02.308056+00:00 app[web.1]: 	/tmp/build_815585c8/app/services/email/smtp/smtp.go:94 +0x180e
2021-05-14T18:14:02.308056+00:00 app[web.1]: reflect.Value.call(0x1a1bb00, 0x1b64918, 0x13, 0x1afd2b6, 0x4, 0xc000207ca0, 0x2, 0x2, 0x19c3668, 0x8, ...)
2021-05-14T18:14:02.308057+00:00 app[web.1]: 	/tmp/codon/tmp/cache/go1.16.1/go/src/reflect/value.go:476 +0x8e7
2021-05-14T18:14:02.308057+00:00 app[web.1]: reflect.Value.Call(0x1a1bb00, 0x1b64918, 0x13, 0xc000207ca0, 0x2, 0x2, 0x85f9f3, 0x1a0ed60, 0x203000)
2021-05-14T18:14:02.308057+00:00 app[web.1]: 	/tmp/codon/tmp/cache/go1.16.1/go/src/reflect/value.go:337 +0xb9
2021-05-14T18:14:02.308058+00:00 app[web.1]: github.com/getfider/fider/app/pkg/bus.Publish(0x1ca4a30, 0xc000412570, 0xc000207d78, 0x1, 0x1)
2021-05-14T18:14:02.308058+00:00 app[web.1]: 	/tmp/build_815585c8/app/pkg/bus/bus.go:152 +0x439
2021-05-14T18:14:02.308059+00:00 app[web.1]: github.com/getfider/fider/app/tasks.SendSignUpEmail.func1(0xc000412570, 0xc000412480, 0x1a0ed60)
2021-05-14T18:14:02.308059+00:00 app[web.1]: 	/tmp/build_815585c8/app/tasks/tasks.go:41 +0x3c7
2021-05-14T18:14:02.308059+00:00 app[web.1]: github.com/getfider/fider/app/middlewares.WorkerSetup.func1.1(0xc000412570, 0x0, 0x0)
2021-05-14T18:14:02.308060+00:00 app[web.1]: 	/tmp/build_815585c8/app/middlewares/setup.go:58 +0x422
2021-05-14T18:14:02.308060+00:00 app[web.1]: github.com/getfider/fider/app/pkg/worker.(*BackgroundWorker).Run(0xc0001d4180, 0x1b34425, 0x2)
2021-05-14T18:14:02.308060+00:00 app[web.1]: 	/tmp/build_815585c8/app/pkg/worker/worker.go:73 +0x26c
2021-05-14T18:14:02.308061+00:00 app[web.1]: created by github.com/getfider/fider/app/pkg/web.(*Engine).Start
2021-05-14T18:14:02.308061+00:00 app[web.1]: 	/tmp/build_815585c8/app/pkg/web/engine.go:125 +0x525
2021-05-14T18:14:02.308062+00:00 app[web.1]:  (app/pkg/errors/errors.go:40)
2021-05-14T18:14:02.308062+00:00 app[web.1]: - github.com/getfider/fider/app/services/email/smtp.sendMail:94 (app/pkg/errors/errors.go:39)
2021-05-14T18:14:02.308062+00:00 app[web.1]: - failed to send email with template signup_email (app/services/email/smtp/smtp.go:94)
2021-05-14T18:14:02.308063+00:00 app[web.1]: - EOF
2021-05-14T18:14:02.308126+00:00 app[web.1]: [1m[34mINFO[0m[0m [2021-05-14T18:14:02Z] [BGW] [cInfPLZ3RNZYJSeOY0LfIctPwqls5uUE] Task '[36mSend sign up email[0m' finished in [36m77429[0mms (panicked)
```

I am not sure why there are some characters in the output that are not visible on my computer.

**Comment by goenning** [comment]
@masteradit what email provider are you using? This is likely to be a configuration error. I’d suggest try different combinations of ports and START_TLS

for reference: https://stackoverflow.com/questions/57063411/go-smtp-unable-to-send-email-through-gmail-getting-eof

**Comment by masteradit** [comment]
@goenning I am using Yandex for my domain. Here are the email related `Config Vars` that I have put in Heroku settings:
`EMAIL_NOREPLY` - `noreply@mydomain.com`
`EMAIL_SMTP_HOST` - `smtp.yandex.com`
`EMAIL_SMTP_PASSWORD` - `passwordOfTheAccount`
`EMAIL_SMTP_PORT` - `465`
`EMAIL_SMTP_USERNAME` - `noreply@mydomain.com`

I used port 465 because it was written here - https://yandex.com/support/mail/mail-clients/others.html

**Comment by goenning** [comment]
Can you try port 587?

**Comment by masteradit** [comment]
@goenning It worked! Thanks a lot!
